language: python
python: 2.7
sudo: false
cache: pip
install:
  - pip install ansible
script:
  - ansible-playbook --syntax-check -i hosts/development dev.yml
  - ansible-playbook --syntax-check -i hosts/development server.yml
  - ansible-playbook --syntax-check -i hosts/development secure-root.yml
